export const exampleData = [
    {
        id: 1,
        description: "Toyota Corolla",
        year: 2017,
        licensePlate: "XYZ-1234",
        mileage: 45234,
        maintenanceStatus: 78,
        available: true,
    },
    {
        id: 2,
        description: "Honda Civic",
        year: 2018,
        licensePlate: "ABC-5678",
        mileage: 37290,
        maintenanceStatus: 85,
        available: false,
    },
    {
        id: 3,
        description: "Ford Focus",
        year: 2019,
        licensePlate: "DEF-9012",
        mileage: 15987,
        maintenanceStatus: 90,
        available: true,
    },
    {
        id: 4,
        description: "Chevrolet Malibu",
        year: 2016,
        licensePlate: "GHI-3456",
        mileage: 67890,
        maintenanceStatus: 65,
        available: false,
    },
    {
        id: 5,
        description: "Nissan Altima",
        year: 2020,
        licensePlate: "JKL-7890",
        mileage: 20500,
        maintenanceStatus: 95,
        available: true,
    },
    {
        id: 6,
        description: "Hyundai Elantra",
        year: 2017,
        licensePlate: "MNO-1234",
        mileage: 48234,
        maintenanceStatus: 80,
        available: false,
    },
    {
        id: 7,
        description: "Kia Optima",
        year: 2018,
        licensePlate: "PQR-5678",
        mileage: 36200,
        maintenanceStatus: 88,
        available: true,
    },
    {
        id: 8,
        description: "Volkswagen Jetta",
        year: 2019,
        licensePlate: "STU-9012",
        mileage: 14500,
        maintenanceStatus: 92,
        available: false,
    },
    {
        id: 9,
        description: "Subaru Impreza",
        year: 2016,
        licensePlate: "VWX-3456",
        mileage: 69000,
        maintenanceStatus: 60,
        available: true,
    },
    {
        id: 10,
        description: "Mazda 3",
        year: 2020,
        licensePlate: "YZA-7890",
        mileage: 21000,
        maintenanceStatus: 93,
        available: true,
    },
    {
        id: 11,
        description: "Toyota Camry",
        year: 2017,
        licensePlate: "XYZ-4321",
        mileage: 50234,
        maintenanceStatus: 77,
        available: false,
    },
    {
        id: 12,
        description: "Honda Accord",
        year: 2018,
        licensePlate: "ABC-8765",
        mileage: 39290,
        maintenanceStatus: 84,
        available: true,
    },
    {
        id: 13,
        description: "Ford Fusion",
        year: 2019,
        licensePlate: "DEF-2109",
        mileage: 16987,
        maintenanceStatus: 89,
        available: false,
    },
    {
        id: 14,
        description: "Chevrolet Impala",
        year: 2016,
        licensePlate: "GHI-6543",
        mileage: 68890,
        maintenanceStatus: 64,
        available: true,
    },
    {
        id: 15,
        description: "Nissan Maxima",
        year: 2020,
        licensePlate: "JKL-0987",
        mileage: 19500,
        maintenanceStatus: 97,
        available: true,
    },
    {
        id: 16,
        description: "Hyundai Sonata",
        year: 2017,
        licensePlate: "MNO-5678",
        mileage: 47234,
        maintenanceStatus: 82,
        available: false,
    },
    {
        id: 17,
        description: "Kia Rio",
        year: 2018,
        licensePlate: "PQR-3456",
        mileage: 35200,
        maintenanceStatus: 86,
        available: true,
    },
    {
        id: 18,
        description: "Volkswagen Passat",
        year: 2019,
        licensePlate: "STU-7890",
        mileage: 13500,
        maintenanceStatus: 91,
        available: false,
    },
    {
        id: 19,
        description: "Subaru Legacy",
        year: 2016,
        licensePlate: "VWX-9012",
        mileage: 68000,
        maintenanceStatus: 63,
        available: true,
    },
    {
        id: 20,
        description: "Mazda 6",
        year: 2020,
        licensePlate: "YZA-2345",
        mileage: 22000,
        maintenanceStatus: 94,
        available: true,
    },
    {
        id: 21,
        description: "Toyota Prius",
        year: 2017,
        licensePlate: "XYZ-5432",
        mileage: 51234,
        maintenanceStatus: 76,
        available: false,
    },
    {
        id: 22,
        description: "Honda Insight",
        year: 2018,
        licensePlate: "ABC-9876",
        mileage: 38290,
        maintenanceStatus: 83,
        available: true,
    },
    {
        id: 23,
        description: "Ford Mustang",
        year: 2019,
        licensePlate: "DEF-3210",
        mileage: 17987,
        maintenanceStatus: 88,
        available: false,
    },
    {
        id: 24,
        description: "Chevrolet Camaro",
        year: 2016,
        licensePlate: "GHI-7654",
        mileage: 69890,
        maintenanceStatus: 62,
        available: true,
    },
    {
        id: 25,
        description: "Nissan Sentra",
        year: 2020,
        licensePlate: "JKL-6789",
        mileage: 18500,
        maintenanceStatus: 96,
        available: true,
    },
    {
        id: 26,
        description: "Hyundai Tucson",
        year: 2017,
        licensePlate: "MNO-6789",
        mileage: 46234,
        maintenanceStatus: 81,
        available: false,
    },
    {
        id: 27,
        description: "Kia Sportage",
        year: 2018,
        licensePlate: "PQR-4321",
        mileage: 34200,
        maintenanceStatus: 87,
        available: true,
    },
    {
        id: 28,
        description: "Volkswagen Tiguan",
        year: 2019,
        licensePlate: "STU-6789",
        mileage: 12500,
        maintenanceStatus: 93,
        available: false,
    },
    {
        id: 29,
        description: "Subaru Forester",
        year: 2016,
        licensePlate: "VWX-7890",
        mileage: 67000,
        maintenanceStatus: 61,
        available: true,
    },
    {
        id: 30,
        description: "Mazda CX-5",
        year: 2020,
        licensePlate: "YZA-5678",
        mileage: 23000,
        maintenanceStatus: 95,
        available: true,
    },
    {
        id: 31,
        description: "Toyota RAV4",
        year: 2017,
        licensePlate: "XYZ-6789",
        mileage: 52234,
        maintenanceStatus: 75,
        available: false,
    },
    {
        id: 32,
        description: "Honda CR-V",
        year: 2018,
        licensePlate: "ABC-5432",
        mileage: 37290,
        maintenanceStatus: 82,
        available: true,
    },
    {
        id: 33,
        description: "Ford Escape",
        year: 2019,
        licensePlate: "DEF-6543",
        mileage: 18987,
        maintenanceStatus: 87,
        available: false,
    },
    {
        id: 34,
        description: "Chevrolet Equinox",
        year: 2016,
        licensePlate: "GHI-4321",
        mileage: 70890,
        maintenanceStatus: 66,
        available: true,
    },
    {
        id: 35,
        description: "Nissan Rogue",
        year: 2020,
        licensePlate: "JKL-5432",
        mileage: 17500,
        maintenanceStatus: 98,
        available: true,
    },
    {
        id: 36,
        description: "Hyundai Santa Fe",
        year: 2017,
        licensePlate: "MNO-3456",
        mileage: 45234,
        maintenanceStatus: 79,
        available: false,
    },
    {
        id: 37,
        description: "Kia Sorento",
        year: 2018,
        licensePlate: "PQR-0987",
        mileage: 33200,
        maintenanceStatus: 85,
        available: true,
    },
    {
        id: 38,
        description: "Volkswagen Atlas",
        year: 2019,
        licensePlate: "STU-1234",
        mileage: 11500,
        maintenanceStatus: 94,
        available: false,
    },
    {
        id: 39,
        description: "Subaru Ascent",
        year: 2016,
        licensePlate: "VWX-6543",
        mileage: 66000,
        maintenanceStatus: 62,
        available: true,
    },
    {
        id: 40,
        description: "Mazda CX-9",
        year: 2020,
        licensePlate: "YZA-7890",
        mileage: 24000,
        maintenanceStatus: 96,
        available: true,
    },
    {
        id: 41,
        description: "Toyota Highlander",
        year: 2017,
        licensePlate: "XYZ-3456",
        mileage: 53234,
        maintenanceStatus: 74,
        available: false,
    },
    {
        id: 42,
        description: "Honda Pilot",
        year: 2018,
        licensePlate: "ABC-6789",
        mileage: 36290,
        maintenanceStatus: 81,
        available: true,
    },
    {
        id: 43,
        description: "Ford Explorer",
        year: 2019,
        licensePlate: "DEF-7890",
        mileage: 19987,
        maintenanceStatus: 86,
        available: false,
    },
    {
        id: 44,
        description: "Chevrolet Traverse",
        year: 2016,
        licensePlate: "GHI-0987",
        mileage: 71890,
        maintenanceStatus: 67,
        available: true,
    },
    {
        id: 45,
        description: "Nissan Murano",
        year: 2020,
        licensePlate: "JKL-1234",
        mileage: 16500,
        maintenanceStatus: 99,
        available: true,
    },
    {
        id: 46,
        description: "Hyundai Palisade",
        year: 2017,
        licensePlate: "MNO-7890",
        mileage: 44234,
        maintenanceStatus: 80,
        available: false,
    },
    {
        id: 47,
        description: "Kia Telluride",
        year: 2018,
        licensePlate: "PQR-1234",
        mileage: 31200,
        maintenanceStatus: 84,
        available: true,
    },
    {
        id: 48,
        description: "Volkswagen Touareg",
        year: 2019,
        licensePlate: "STU-3456",
        mileage: 10500,
        maintenanceStatus: 95,
        available: false,
    },
    {
        id: 49,
        description: "Subaru Crosstrek",
        year: 2016,
        licensePlate: "VWX-7890",
        mileage: 65000,
        maintenanceStatus: 64,
        available: true,
    },
    {
        id: 50,
        description: "Mazda CX-30",
        year: 2020,
        licensePlate: "YZA-2345",
        mileage: 25000,
        maintenanceStatus: 97,
        available: true,
    },
];
